### ISSUE TITLE
Add babel => es5 => rollup

### ISSUE THREAD

**Issue by samccone** [samccone/The-cost-of-transpiling-es2015-in-2016#1]
babel needs to be set to loose mode

**Comment by samccone** [comment]
done

**Comment by samccone** [comment]
https://github.com/samccone/es6-es3-showdown/commit/337ecbce2cbafd44681b305a271de2bd82b9d979

**Comment by hzoo** [comment]
Doesn't look like the loose versions of plugins are being used, just the es2015 preset?

Right now we don't have a way to pass options down until https://github.com/babel/babel/pull/3331 so it'd have to be one by one or use a preset someone made

**Comment by samccone** [comment]
PRs welcome if you think it will improve the metrics :)

**Comment by hzoo** [comment]
I'm not sure so we'll have to try, although once something like https://github.com/babel/babel/pull/3331 is in, the PR will be easier anyway :smile:
