### ISSUE TITLE
Misleading graph: start-at-zero rule

### ISSUE THREAD

**Issue by callumacrae** [samccone/The-cost-of-transpiling-es2015-in-2016#16]
Hello!

Thanks for this project. It's really interesting, and might finally convince me to move our browserify setup to webpack!

However, I object to [this graph](https://cloud.githubusercontent.com/assets/883126/12737115/d9445784-c90a-11e5-8e6e-ab38a74a16ee.png). Bar charts should basically _never_ not be indexed from zero, and while I completely agree with your point, I find this graph super misleading! At first glance, I thought the difference was a lot greater than it actually is.

https://en.wikipedia.org/wiki/Wikipedia:Don%27t_draw_misleading_graphs

Sorry for the nitpicking.

**Comment by samccone** [comment]
nah good point, when I update the graph tonight with all of the new results I will set it to zero.

Thanks!

**Comment by callumacrae** [comment]
Awesome, thank you!

Thanks again for your work on this :ok_hand:

**Comment by samccone** [comment]
fixed thx

**Comment by samccone** [comment]
![image](https://cloud.githubusercontent.com/assets/883126/12774177/2b64564e-c9f7-11e5-9b77-f3425e0020b6.png)
