### ISSUE TITLE
Add bundle-collapser plugin for browserify

### ISSUE THREAD

**Issue by WickyNilliams** [samccone/The-cost-of-transpiling-es2015-in-2016#19]
I'm not sure why browserify doesn't do this by default, but you get quite substantial savings by using the bundle-collapser plugin. This converts the string module paths to integers.

Since webpack does this by default, it seems fair to use this for a more even comparison:
https://github.com/substack/bundle-collapser

**Comment by samccone** [comment]
@WickyNilliams PR is more than welcome to add this :)

**Comment by paulirish** [comment]
tbh i would be surprised the savings is significant after gzip

**Comment by nstepien** [comment]
@samccone You can close this one too now.

**Comment by samccone** [comment]
:+1: thx @MayhemYDG

**Comment by WickyNilliams** [comment]
Thanks @MayhemYDG, beat me to it :)
