### ISSUE TITLE
per bundle overhead vs per module overhead

### ISSUE THREAD

**Issue by calvinmetcalf** [samccone/The-cost-of-transpiling-es2015-in-2016#35]
it might be helpful testing larger bundles, some bundlers may have high overhead that is only added once per bundle while others may have overhead that is added once per module or something, aka big bundles may behave different then small bundles

**Comment by samccone** [comment]
@calvinmetcalf if you have a large OSS vanilla es6 project that has a set of tests I would be more than willing to swap it out.

I used the todomvc example because it fit all of these requirements :)

**Comment by calvinmetcalf** [comment]
I was thinking in addition to todomvc, PouchDB might be an option though I
believe it is written with rollups dead code elimination in mind so it
might be a little biased.

**Comment by samccone** [comment]
xref
https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016/issues/38

going to close but... if someone wants to open a PR that can be compiled across all of the examples here... more than willing to land it!
