### ISSUE TITLE
Mention real-world scenarios

### ISSUE THREAD

**Issue by boneskull** [samccone/The-cost-of-transpiling-es2015-in-2016#41]
Hi. Great work here. 

Doesn't `rollup` only work with ES6 modules though?  This means you can't gain its benefits fully unless not only your code uses them, but all your deps as well?

I'm worried presenting the analysis in this manner, while helpful for comparison's sake, is somewhat misleading for real-world use cases. A novice to the murky waters of JS tooling may end up wasting time trying to achieve similar results. :smile:

I'm excited for the possibilities of tools like `rollup` in the future. Perhaps it's worth mentioning the caveat. If you did already and I missed it, sorry! Or sorry also if I'm misinformed on how `rollup` works...

**Comment by samccone** [comment]
yep based on what I know rollup is just es6.

This repo is intended to show the overhead and compile efficiency across multiple tools... all that suport es2015 -> es5.

Feel free to open a PR to clarify how this could be made better.

Thanks for the issue :+1:
