### ISSUE TITLE
Usefulness of JS compile+execute time in graphic

### ISSUE THREAD

**Issue by dbkaplun** [samccone/The-cost-of-transpiling-es2015-in-2016#45]
What is the logic behind showing JS compile+execute time as one bar in this graphic? One is server-side and happens once and the other is client-side and happens every time the client runs the page. It seems that the two numbers should not be related.

![graphic](https://cloud.githubusercontent.com/assets/883126/12903661/453405a2-ce7e-11e5-9ddf-389f4ef8f60f.png)

**Comment by samccone** [comment]
> from the readme doc

```
*js execution time on page load (gathered by big-rig)
*js compile time (gathered by big-rig)
```

---

These are both front-end metrics, the javascript gets compiled by the JIT and then executes :)

Thanks for the issue.

**Comment by dbkaplun** [comment]
Ah, that explains it. "js compile time" is a bit confusing though, maybe it warrants additional explanation? Anyway thanks!
