### ISSUE TITLE
Better explanation of the findings?

### ISSUE THREAD

**Issue by corysimmons** [samccone/The-cost-of-transpiling-es2015-in-2016#50]
Thoughts on augmenting the README or writing a blog post about what each of the findings actually means?

I kind of understand them, but it'd be a lot nicer if there was just a definitive "This way is the best way for visitors".

I thought I was just a JS idiot, but I've asked a few of my JS-capable friends and they're unsure as well so maybe it's worth doing?

**Comment by samccone** [comment]
Hmm what kind of breakdown are you looking for?

**Comment by corysimmons** [comment]
Like what does filesize actually mean to someone on a 15Mbps connection or 3g connection? How many ms difference are we talking here? Does JS compile time and tool run time mean anything to the end user?

Basically just a big fat "This one provides an objectively faster experience to the end user".

I suppose my issue is that https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016#raw-data makes it seem like Closure is the fastest because it's the smallest, but then I notice js execution time is the fastest on `babelify + uglify`. So I suppose this means people will download/cache the file once, then have a better experience with `babelify + uglify`? I like that the data is here, but I really just want someone smart to tell me which combo is better in various situations.
